# This is the Continuous Integration (CI) pipeline.
#
# Its sole purpose is to guard the `main` branch. It runs on every push
# to `main` and ensures that all code meets the highest standards of quality
# and security across multiple operating systems.
#
# This pipeline must pass before a release can be safely created.

name: Continuous Integration

on:
  push:
    branches:
      - main

# Set default permissions for the GITHUB_TOKEN.
permissions:
  contents: read

jobs:
  quality_and_security_shield:
    name: Cross-Platform Quality & Security Shield
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ matrix.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ matrix.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Scan for code vulnerabilities with bandit
        run: bandit -r . -ll -ii

      - name: Scan for dependency vulnerabilities with pip-audit
        run: pip-audit

      - name: Run tests and collect coverage
        run: pytest --cov=src --cov-report=xml

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: ${{ matrix.os }}
          fail_ci_if_error: true
