name: Ultimate Deploy, Scan, and Notify

# Triggers
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}
  # If you want a schedule as well, uncomment:
  # schedule:
  #   - cron: "0 * * * *"  # every hour (UTC)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Required for OIDC auth steps
permissions:
  contents: read
  id-token: write

env:
  # Default timeouts (can be overridden per-job)
  TCP_TIMEOUT: "3.0"
  HTTP_TIMEOUT: "5.0"
  DOWNLOAD_TIMEOUT: "8.0"
  CONNECTION_TIMEOUT: "4.0"
  STRICT: "false"    # set to "true" to make CI strict (fail on lint/test errors)

################################################################
# 0) Preflight: check required files and secrets (fail-fast)
################################################################
jobs:
  preflight:
    name: Preflight validations
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check.outputs.ok }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure required scripts/files and secrets are present
        id: check
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCP_WI_PROVIDER: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          missing=()
          # Check for required local files (add more if needed)
          for f in scripts/deploy_firebase.sh src/fetcher.py src/xray_tester.py; do
            if [ ! -e "$f" ]; then
              missing+=("$f")
            fi
          done

          # Require at least one deployment credential method
          if [ -z "${FIREBASE_TOKEN:-}" ] && [ -z "${GCP_WI_PROVIDER:-}" ]; then
            missing+=("FIREBASE_TOKEN or GCP_WORKLOAD_IDENTITY_PROVIDER (one required to deploy/notify)")
          fi

          if [ ${#missing[@]} -ne 0 ]; then
            echo "Missing required items:"
            for m in "${missing[@]}"; do echo " - $m"; done
            echo "ok=false" >> $GITHUB_OUTPUT
            exit 1
          fi

          echo "ok=true" >> $GITHUB_OUTPUT

################################################################
# 1) Quality & Security (CI matrix)
################################################################
  quality_and_security_shield:
    name: Cross-Platform Quality & Security Shield
    needs: preflight
    if: needs.preflight.outputs.ok == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]   # add windows if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install requirements (if present)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          else
            echo "requirements.txt not found, skipping."
          fi

      - name: Install dev tools (lint/test/security)
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 bandit pip-audit pytest

      - name: Lint (flake8) — configurable strictness
        env:
          STRICT: ${{ env.STRICT }}
        run: |
          if [ "${STRICT}" = "true" ]; then
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          else
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
          fi

      - name: Security scan: bandit
        run: |
          bandit -r . -ll -ii || true

      - name: Dependency scan: pip-audit
        run: |
          pip-audit || true

      - name: Run tests + collect coverage
        id: run_tests
        run: |
          set -euo pipefail
          coverage_exists=false

          if python -m pytest --cov=src --cov-report=xml; then
            if [ -f coverage.xml ]; then
              coverage_exists=true
            fi
          else
            echo "pytest returned non-zero exit code"
            if [ "${STRICT}" = "true" ]; then
              exit 1
            fi
          fi

          echo "coverage_exists=${coverage_exists}" >> $GITHUB_OUTPUT

      - name: Upload coverage to Codecov (only when coverage exists)
        if: steps.run_tests.outputs.coverage_exists == 'true'
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: ${{ matrix.os }}
          fail_ci_if_error: true

################################################################
# 2) Build & Scan (fetch → test → filter → report)
################################################################
  build_and_scan:
    name: Build and Scan
    needs: [preflight, quality_and_security_shield]
    if: needs.preflight.outputs.ok == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 40
    outputs:
      proxy_count: ${{ steps.count_proxies.outputs.count }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Restore pip cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ubuntu-latest-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ubuntu-latest-pip-

      - name: Install dependencies (if exist)
        run: |
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi

      - name: Install application components (cores) if needed
        id: install_cores
        run: |
          if [ -f install.py ]; then
            python install.py || echo "install.py failed (check logs)"
          else
            echo "install.py not present - skipping cores install"
          fi

      - name: 1. Fetch Subscription Sources
        run: |
          set -e
          python3 -m src.fetcher

      - name: 2. Test Proxies (Xray)
        run: python3 -m src.xray_tester

      - name: 3. Test Proxies (Hiddify)
        run: python3 -m src.hiddify_tester

      - name: 4. Filter and Generate Lists
        run: python3 -m src.filter

      - name: 5. Generate Final Reports
        run: python3 -m src.reporter

      - name: 6. Self-Verification Gate
        run: python3 scripts/verify_output.py

      - name: Count Proxies (always runs)
        id: count_proxies
        if: always()
        run: |
          set -euo pipefail
          cnt=0
          if [ -f output/all.txt ]; then
            cnt=$(wc -l < output/all.txt | tr -d ' ')
          fi
          echo "Found $cnt proxies."
          echo "count=$cnt" >> $GITHUB_OUTPUT

      - name: Ensure artifact dirs exist (avoid upload failure)
        if: always()
        run: |
          mkdir -p output logs
          if [ ! -f output/.placeholder ]; then touch output/.placeholder; fi

      - name: Upload scan results and logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: scan-results
          path: |
            output/
            logs/
          retention-days: 7

################################################################
# 3) Deploy (Firebase)
################################################################
  deploy:
    name: Deploy to Firebase
    needs: build_and_scan
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: needs.preflight.outputs.ok == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node & firebase-tools
        run: |
          # Install firebase-tools if missing
          if ! command -v firebase >/dev/null 2>&1; then
            npm install -g firebase-tools
          fi
          firebase --version || true

      - name: Make deploy script executable
        run: |
          if [ -f scripts/deploy_firebase.sh ]; then chmod +x scripts/deploy_firebase.sh; fi

      - name: Deploy to Firebase (prefer FIREBASE_TOKEN; fallback => guidance)
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          set -euo pipefail
          if [ -n "${FIREBASE_TOKEN:-}" ]; then
            echo "Using FIREBASE_TOKEN to deploy."
            ./scripts/deploy_firebase.sh
          else
            echo "FIREBASE_TOKEN is not provided. To deploy without a token, configure Workload Identity (OIDC) and update this job."
            exit 1
          fi

################################################################
# 4) Notify Users (FCM) — uses OIDC / Workload Identity
################################################################
  notify_users:
    name: Notify Users (FCM)
    needs: [deploy, build_and_scan]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: needs.preflight.outputs.ok == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate using Workload Identity
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Get access token
        id: get_token
        run: |
          ACCESS_TOKEN=$(gcloud auth print-access-token)
          echo "access_token=${ACCESS_TOKEN}" >> $GITHUB_OUTPUT

      - name: Send FCM notification (data-driven)
        env:
          PROXY_COUNT: ${{ needs.build_and_scan.outputs.proxy_count }}
          ACCESS_TOKEN: ${{ steps.get_token.outputs.access_token }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          set -euo pipefail
          TITLE="Proxies Updated"
          BODY="${PROXY_COUNT} new proxies are available!"
          cat > /tmp/fcm_payload.json <<EOF
{
  "message": {
    "topic": "news",
    "notification": {
      "title": "${TITLE}",
      "body": "${BODY}"
    },
    "data": {
      "update_type": "proxy_list",
      "proxy_count": "${PROXY_COUNT}",
      "timestamp": "$(date +%s)"
    }
  }
}
EOF
          curl -sS -X POST "https://fcm.googleapis.com/v1/projects/${GCP_PROJECT_ID}/messages:send" \
            -H "Authorization: Bearer ${ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            -d @/tmp/fcm_payload.json
