# CI — Super Pipeline
# Automatically runs every hour (UTC) and can be triggered manually.
# Purpose: robust linting, testing, static analysis, security scans, build, and artifact collection
# Designed to work for mixed Python + Go repositories (auto-detects sources)

name: CI — Super Pipeline (Hourly & Manual)

on:
  schedule:
    # runs every hour at minute 0 (GitHub Actions uses UTC for schedule)
    - cron: '0 * * * *'
  workflow_dispatch:
    inputs:
      skip_docker:
        description: 'Set to true to skip Docker build & scan when running manually'
        required: false
        default: 'false'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  id-token: write

env:
  PYTEST_JUNIT: reports/junit.xml

jobs:
  prepare:
    name: Prepare environment & cache
    runs-on: ubuntu-latest
    outputs:
      go-version: 1.21.x
      python-version: 3.11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup QEMU (optional, for cross-platform container builds)
        uses: docker/setup-qemu-action@v2

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git curl jq build-essential

      - name: Install Python dev tools (if Python sources exist)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install --upgrade ruff mypy pytest pytest-asyncio pip-audit bandit pre-commit || true

      - name: Install golangci-lint (if Go sources exist)
        run: |
          if find . -name '*.go' | grep -q .; then
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $HOME/bin v1.54.2
            echo "$HOME/bin" >> $GITHUB_PATH
          else
            echo "no go files detected, skipping golangci-lint install"
          fi

  lint:
    name: Lint (Python + Go)
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v4

      - name: Restore caches (pip/go)
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-combined-${{ hashFiles('**/go.sum','**/requirements.txt') }}

      - name: Run ruff (Python linter/formatter)
        run: |
          if command -v ruff >/dev/null 2>&1 && (ls **/*.py >/dev/null 2>&1 || ls *.py >/dev/null 2>&1); then
            ruff check .
          else
            echo "ruff not present or no python files found, skipping"
          fi

      - name: Run mypy (optional static typing)
        run: |
          if command -v mypy >/dev/null 2>&1 && (ls **/*.py >/dev/null 2>&1 || ls *.py >/dev/null 2>&1); then
            mypy --ignore-missing-imports || echo "mypy issues (non-blocking)"
          else
            echo "mypy not present or no python files found, skipping"
          fi

      - name: Run golangci-lint (Go)
        run: |
          if command -v golangci-lint >/dev/null 2>&1 && find . -name '*.go' | grep -q .; then
            golangci-lint run ./...
          else
            echo "golangci-lint not present or no go files found, skipping"
          fi

  unit-tests:
    name: Unit & Integration tests (Python + Go)
    runs-on: ubuntu-latest
    needs: prepare
    strategy:
      fail-fast: true
      matrix:
        language: [python, go]
    steps:
      - uses: actions/checkout@v4

      - name: Setup tooling for matrix
        run: |
          if [ "${{ matrix.language }}" = "python" ]; then
            python -m pip install --upgrade pip
            pip install pytest pytest-asyncio
          else
            echo "Go matrix: ensuring module cache"
            go env -w GO111MODULE=on || true
          fi

      - name: Run pytest (Python)
        if: matrix.language == 'python'
        run: |
          if [ -f pytest.ini ] || [ -d tests ] || ls **/*_test.py >/dev/null 2>&1 || ls *_test.py >/dev/null 2>&1; then
            mkdir -p reports
            pytest -q --maxfail=1 --junitxml=${{ env.PYTEST_JUNIT }}
          else
            echo "no python tests detected, skipping pytest"
          fi

      - name: Run go test (Go)
        if: matrix.language == 'go'
        run: |
          if find . -name '*_test.go' | grep -q .; then
            go test ./... -count=1 -v
          else
            echo "no go tests detected, skipping go test"
          fi

      - name: Upload test reports (JUnit)
        if: matrix.language == 'python'
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: ${{ env.PYTEST_JUNIT }}

  static-security:
    name: Static & Security scans
    runs-on: ubuntu-latest
    needs: [prepare]
    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: 'python,go'

      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@v3

      - name: pip-audit (Python dependencies)
        run: |
          if [ -f requirements.txt ]; then
            pip-audit --progress wheel
          else
            echo "no requirements.txt found, skipping pip-audit"
          fi

      - name: Bandit security scan (Python)
        run: |
          if ls **/*.py >/dev/null 2>&1 || ls *.py >/dev/null 2>&1; then
            bandit -r . -ll || echo "bandit reported issues"
          else
            echo "no python files found, skipping bandit"
          fi

      - name: gosec (Go security)
        run: |
          if find . -name '*.go' | grep -q .; then
            curl -sSfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | bash -s -- -b $HOME/bin
            echo "$HOME/bin" >> $GITHUB_PATH
            $HOME/bin/gosec ./...
          else
            echo "no go files found, skipping gosec"
          fi

  build:
    name: Build & Package
    runs-on: ubuntu-latest
    needs: [unit-tests, lint]
    steps:
      - uses: actions/checkout@v4

      - name: Build Go binaries
        run: |
          if find . -name '*.go' | grep -q .; then
            mkdir -p build/bin
            go env -w GO111MODULE=on || true
            # build all main packages under cmd/ (if present) otherwise try top-level
            if [ -d cmd ]; then
              for d in cmd/*; do
                if [ -f "$d" ]; then continue; fi
                pkg=$(basename "$d")
                go build -o build/bin/${pkg} ./cmd/${pkg} || true
              done
            else
              go build -o build/bin/app ./... || true
            fi
          else
            echo "no go files to build"
          fi

      - name: Build Python wheel
        run: |
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            python -m pip install build
            python -m build
          else
            echo "no python packaging metadata found, skipping wheel build"
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            build/**
            dist/**

  container-scan:
    name: Docker Build & Trivy Scan (if Dockerfile exists)
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.skip_docker != 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Check for Dockerfile
        id: dockerfile-check
        run: |
          if [ -f Dockerfile ]; then echo "true"; else echo "false"; fi

      - name: Build Docker image (no push)
        if: steps.dockerfile-check.outputs == '' || steps.dockerfile-check.outputs == 'true'
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:ci-${{ github.run_id }}

      - name: Scan image with Trivy
        if: steps.dockerfile-check.outputs == '' || steps.dockerfile-check.outputs == 'true'
        uses: aquasecurity/trivy-action@v1
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:ci-${{ github.run_id }}
          format: table

  reports:
    name: Collect logs & reports
    runs-on: ubuntu-latest
    needs: [lint, unit-tests, static-security, build]
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: ci-logs-and-reports
          path: |
            **/*.log
            reports/**
            build/**
            dist/**
            .github/workflows/**

# End of workflow
# Notes for maintainers:
# - Cron schedules are in UTC. If you need a different timezone, convert to UTC or use calendar-based triggers.
# - Add repository secrets when you want to enable publishing (DOCKERHUB_TOKEN, GHCR_PAT, FIREBASE_TOKEN, etc.)
# - The workflow auto-detects Python and Go sources and skips irrelevant steps to avoid noisy failures.
# - For very large repositories, tune caching keys and split jobs further to optimize runtime and parallelism.
