name: Proxy Scan & Report

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch: # Allow manual runs

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
    - name:  checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip' # Cache dependencies

    - name: Run Installer
      run: python install.py

    - name: Run scanner
      run: python -m src.main

    - name: Commit Results
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add output/
        git diff --staged --quiet || git commit -m "Update proxy subscription and report"
        git push
